# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Country code')),
                ('name', models.CharField(max_length=50, verbose_name='Country name')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='State/Province name')),
                ('code', models.CharField(blank=True, max_length=5, verbose_name='State Code')),
                ('country_code', models.CharField(max_length=2, verbose_name='Country code')),
                ('timezone', models.CharField(max_length=128, verbose_name='Timezone')),
            ],
            options={
                'ordering': ('country_code', 'name'),
            },
        ),
    ]
